package ClientAndServer;


/**
* ClientAndServer/HelloWorld.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 22 March 2017 14:05:02 o'clock GMT
*/

public interface HelloWorld extends HelloWorldOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HelloWorld
