package ClientAndServer;


/**
* ClientAndServer/RelayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 23 March 2017 15:34:07 o'clock GMT
*/

public interface RelayOperations 
{
  String fetch_message ();
} // interface RelayOperations
