package ClientAndServer;


/**
* ClientAndServer/Relay.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 23 March 2017 13:32:18 o'clock GMT
*/

public interface Relay extends RelayOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Relay
