// Example of a "relay" - a client and server.
// Uses the old favourite Hello World as a basis.

module ClientAndServer {
    interface Relay {
        string fetch_message();
    };

    interface HelloWorld {
	string hello_world();
    };			
};
